# Generated by Django 5.2.4 on 2025-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drill", "0002_auto_20250711_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="dependent",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
