FROM ubuntu:24.04

LABEL maintainer="Felipe Bañados Schwerter <banadoss@ualberta.ca>"

ARG OAHPA_UID_GID=60006

RUN apt-get update && apt-get install -y python3.12 uwsgi-plugin-python3 pipenv curl sqlite3 gettext supervisor nginx

RUN curl https://apertium.projectjj.com/apt/install-nightly.sh | bash

RUN apt-get update && apt-get install -y --no-install-recommends hfst 

# types.Create the non-root user/group that will own the application code
#RUN groupadd --gid ${OAHPA_UID_GID} oahpa \
# && useradd --no-log-init --gid oahpa \
#    --uid ${OAHPA_UID_GID} oahpa --create-home

# Install and build dependencies,
# then remove build-time dependencies to keep the image slim!
RUN  mkdir /app/ # \
# && chown oahpa /app

# As the non-root user...
#USER oahpa

# Set working directory
WORKDIR /app

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy
RUN mkdir /app/crk_oahpa_project

# Configuration files
COPY containerized_deploy/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY containerized_deploy/uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY containerized_deploy/nginx.conf /etc/nginx/nginx.conf
COPY containerized_deploy/my.cnf /etc/mysql/my.cnf

# numra needs this
COPY containerized_deploy/lookup /usr/local/bin/lookup

# media is served statically directly from the root by nginx
# TODO I believe this is the same folder for every instance, but unsure
#      (It should be!)
# TODO Call instead to collectstatic
RUN mkdir /var/www/html/static
COPY containerized_deploy/media /var/www/html/static

COPY containerized_deploy/uwsgi_vassals /etc/uwsgi/vassals

# Copy in files we need to run the project vessels
COPY crk_oahpa_project /app/crk_oahpa_project

# Copy settings_not_in_svn.py to where it needs to be.
RUN cp /app/crk_oahpa_project/settings_not_in_svn.py /app/crk_oahpa_project/crk_oahpa/settings_not_in_svn.py

# This replaces the SECRET_KEY = '...' with a new secret key for each lang
COPY containerized_deploy/roll_keys.sh /tmp/roll_keys.sh
RUN /tmp/roll_keys.sh

# Compile translations for all instances
RUN cd /app && pipenv run django-admin compilemessages
RUN cd /app/crk_oahpa_project && pipenv run python manage.py migrate

# Execute database initialization script
RUN cd /app/crk_oahpa_project && pipenv run bash parafedaba.sh
# Create logfile
RUN mkdir -p /var/log/uwsgi/ && touch /var/log/uwsgi/crk_oahpa.log

RUN echo "virtualenv = $(pipenv --venv)" >> /etc/uwsgi/vassals/crk_oahpa.ini

CMD [ "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf" ]

