pid /var/run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    #upstream oahpa {
    #    include uwsgi_params;
    #    uwsgi_pass unix:///tmp/uwsgi.sock;
    #}

    server {
        listen 80 default_server;

        # crk
        location /nehiyawetan/media/ {
            rewrite /nehiyawetan/media/(.*) /$1 break;
            root /var/www/html;
        }
        #location ~ ^/nehiyawetan/(.*)$ {
        location /nehiyawetan/ {
            #proxy_pass http://127.0.0.1:8100/nehiyawetan/$1?$args ;
            proxy_pass http://127.0.0.1:8100;
            #proxy_redirect   http://127.0.0.1:8100/ http://oahpa.no/;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $remote_addr;
        }

        location /nehiyawetan {
            rewrite /nehiyawetan /nehiyawetan/ permanent;
        }

        # these were on gtoahpa
        location / {
            #root /home/oahpa/public_html/;
            root /var/www/html;
            index  index.html index.htm;
        }

    }
}
